### ISSUE TITLE
Can't have access to my blog

### ISSUE THREAD

**Issue by brq417059** [hexojs/hexo#1138]
This is the first time I use hexo. I install hexo 3.0. Then I met several problems.

I created a CNAME file with my own domain in, then I created an A record with my DNS provider that resolves the IP addresses: 192.30.252.153

Before, I can visit my blog through username@github.io but not my domain. After doing the thing above,
through neither of them I can access my blog.

**Comment by jr0cket** [comment]
My initial thought is that the DNS record has not yet had time to update across the Internet.  This can take up to 24 hours.

If it has been more than 24 hours since you added your A record, then delete the CNAME file from your Github pages repository and see if that makes a difference.

Then try accessing your site via `http://username.github.io`

**Comment by brq417059** [comment]
Thank you, I'll wait and see then close the issue.
I'm a freshman.,so its a little bit excruciating.Actually, I hardly
fell asleep last night.
