### ISSUE TITLE
Spaced string in imgTag

### ISSUE THREAD

**Issue by ianrose** [hexojs/hexo#1277]
Hexo v3.0

Using the img tag plugin the Alt attribute gets rendered as part of the the title attribute.

Example code used to test:

```
{% img class-name /path/to/image 100 100 "Title" "Alt" %}
```

HTML Output

``` html
<img src="/path/to/image" class="class-name" width="100" height="100" title="Title Alt">
```

**Comment by chenneal** [comment]
I have the question  the same as you don‘t sloved， i don't know the reason.

**Comment by PhiLhoSoft** [comment]
I looked into the source code.
`plugins/tag/img.js` -> `function imgTag(args, content)`
`content` is not used, `args` is populated with a naive split on space of the content of the tag (minus the name of the tag itself, of course).
"Naive" because if you type two spaces in the tag, that will make an empty arg and will shift the next ones, so everything is off.
Moreover, the split removed all quotes!
So, if I have the tag:
`{% img /assets/images/Work-in-Progress.svg 240 75 "Work in Progress" "Work in Progress" %}`
I get the array:

```
[ '/assets/images/Work-in-Progress.svg',
  '240', // Here I got another '', because I added a space between the two numbers...
  '75',
  'Work',
  'in',
  'Progress',
  'Work',
  'in',
  'Progress' ]
```
Once the dimensions are processed, the code does: `meta = args.join(' ');` to get back the title and alt attributes together, then use a regular expression (expecting quoted strings) to split them again.
Problem: there is no longer any quotes, so all we get is the title itself. :cry: 

To fix that, I have to look how the content of a tag is split...

PS.: The problem dates back to May 16! Nobody had the time to fix that? (I know, that's something that can be done by contributors...)

**Comment by PhiLhoSoft** [comment]
OK, I found a workaround...
Just use both kinds of quotes around your title and alt strings!
`{% img /assets/images/Work-in-Progress.svg 240 75 '"Work in Progress"' '"Work in Progress"' %}`
or
`{% img /assets/images/Work-in-Progress.svg 240 75 "'Work in Progress'" "'Work in Progress'" %}`

Apparently, it might be Swig's fault for bad parsing of the parameters...

**Comment by chenneal** [comment]
@PhiLhoSoft  thanks very much, it's looks works through your workaround.

**Comment by PhiLhoSoft** [comment]
@Xuanwo Why did you close this issue? It is not solved at all! I just gave a workaround.
At best, you find a way to make it work as expected, ie. with regular (not doubled) quotes. Might need something on Hexo side, or something on Swing side, from monkey patching the faulty function, to opening an issue at this project.
At worst, this needs at least a documentation update to tell users to use the workaround...

**Comment by Xuanwo** [comment]
Sorry for miss leading for closing the issue when I hadn't read it.

**Comment by tomap** [comment]
Maybe this PR will solve your issue ? https://github.com/hexojs/hexo/pull/2949

**Comment by curbengh** [comment]
imgTag first parse title and alt from the 6th argument, then split them.

https://github.com/hexojs/hexo/blob/f37557ab9cd6cfbd49153f476cd29a50f055eb84/lib/plugins/tag/img.js#L13

`{% img class-name /path/to/image 100 100 '"Title" "Alt"' %}`

Note the usage is different from the [previous comment](https://github.com/hexojs/hexo/issues/1277#issuecomment-165827291), as there is only a pair of single quote.

The doc also shows title and alt are parsed from the 6th argument.

`{% img [class names] /path/to/image [width] [height] "title text 'alt text'" %}`

This means imgTag currently doesn't support parsing alt from the 7th argument.

I'll make a patch to support 7th argument.
