### ISSUE TITLE
Indexing content in Algolia

### ISSUE THREAD

**Issue by borisschapira** [hexojs/hexo#1308]
Hi guys,

I'm trying to develop a new plugin, allowing users to index content in Algolia Search API (a full nodejs SaaS Search Engine). I began a small project to do that : [hexo-algolia](https://www.npmjs.com/package/hexo-algolia).

I'm not sure I'm going **in the good direction**. What I need : a process that would determine if a content has been modified and then add or update it through the Algolia API.

Hence, several questions : 
- Is there a way to determine if a content has been modified through Hexo (i could calculate a file signature if need be) ?
- Is there a way to determine the unicity of a content (by an Id, for exemple)
- Is there a way, during the generator process, to alter a content (for example, if I add a content to the DB, the DB respond me with a unique Id. Is there a way to persist this unique id) ?
- Do you think that the generator approach is the best for User eXperience ? I honestly hesitate to transform my generator into a console command, but I do not know how to get the content in JS object format through this extension type.

Thanks in advance for your answers :+1:

**Comment by tommy351** [comment]
- Hexo calculates the checksum of files to determine whether files are changed. But users can't get the checksum directly so far. The only way you can know the status of files is in [processor plugins][1].
- Every entries in the data model have a unique ID generated with [cuid][2].
- It's not recommended to modify contents in the generator. You should do that in the processor.
- This approach may be confused and I'm still thinking a better way to solve this.

[1]: http://hexo.io/api/box.html#Processors
[2]: https://github.com/ericelliott/cuid

**Comment by borisschapira** [comment]
For now I've developped the extension as a composition of several things.

1/ I created an "algolia" command
2/ I registered to the "before_post_render" filter, so that I would be able to identify all posts during generation
3/ I subscribe to the generateAfter event so that in the end, I would be able to push all the content to Algolia
4/ I launch the generation (obviously)

So far, so good, I can index my content but it's not optimised : all the content is pushed to the service every time, even if nothing has changed. Is it not possible to have a status in the data telling us if the object has changed ?

Moreover, is there an equivalent of the "before_post_render" filter for pages so that I could index pages as well ?

**Comment by borisschapira** [comment]
Processor approach does not satisfy me because I want to index rendered content, not the markdown content in the files parsed. Or else, I need to add a "processor" step to my process, in order to determine if the file has been modified or not, but I can't manage to know where I would find the reference... I've found some code in Hexo manipulating shasum streams, but nothing I could use from outside.

**Comment by leesei** [comment]
@tommy351 Now that hexo/site is using Agolia (mostly in this commit https://github.com/hexojs/site/commit/a3961d9cd3958141cebf8f02c13c9849fe7cf421), is there any insight on how to use Agolia in Hexo?

**Comment by oncletom** [comment]
@leesei Algolia DocSearch relies on scrapping the website (they do it for you), not by indexing content from your end.

"New content" is hard to define: from a CI perspective, each build will be clean so each file will be new anyway. There are probably several approaches to consider:

- comparing the local list of cuid (especially if they do not change per article between two CI builds, otherwise by filepath) with the remote Algolia index in batch, and index those which have changed (checksum is a great indication for that)
- generating an algolia index file which caches the post cuids + checksums – the benefit of this one is it can be cached between two builds ([with Travis CI for example](https://docs.travis-ci.com/user/caching/))

In any case, `hexo.load()` should happen before the execution of the console plugin (I do not know if we can control this – `hexo.on('ready')` maybe?) and the cuid/checksums should be accessible from the `hexo` variable (although it is unclear from an API perspective, where should we look to tap into the list of loaded articles/pages and how to iterate over them).
