### ISSUE TITLE
Mac安装不了hexo啊

### ISSUE THREAD

**Issue by sakz** [hexojs/hexo#1326]
npm install -g hexo-cli

npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "hexo-cli"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! path /usr/local/lib/node_modules/hexo-cli
npm ERR! code EACCES
npm ERR! errno -13

npm ERR! Error: EACCES, rmdir '/usr/local/lib/node_modules/hexo-cli'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES, rmdir '/usr/local/lib/node_modules/hexo-cli']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/usr/local/lib/node_modules/hexo-cli' }
npm ERR!
npm ERR! Please try running this command again as root/Administrator.
npm ERR! error rolling back Error: EACCES, rmdir '/usr/local/lib/node_modules/hexo-cli'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  { [Error: EACCES, rmdir '/usr/local/lib/node_modules/hexo-cli']
npm ERR! error rolling back   errno: -13,
npm ERR! error rolling back   code: 'EACCES',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/hexo-cli' }

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/saber/npm-debug.log

**Comment by tommy351** [comment]
`npm ERR! Please try running this command again as root/Administrator.`

**Comment by sakz** [comment]
hexo deploy
{ [Error: Cannot find module './build/Release/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/default/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/Debug/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
ERROR Deployer not found: github


how to solve this problem

**Comment by Xuanwo** [comment]
run `npm install hexo-deployer-git --save`
and than use `git` instead of `github`

**Comment by TissueFluid** [comment]
@Xuanwo than => then

**Comment by Xuanwo** [comment]
@TissueFluid gg, sorry for my poor english

**Comment by sakz** [comment]
sudo npm install hexo-cli -g
Password:
\
> fsevents@0.3.6 install /usr/local/lib/node_modules/hexo-cli/node_modules/hexo-fs/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: EPERM, utime '/Users/saber/.node-gyp/0.12.4'
gyp ERR! stack     at Error (native)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/hexo-cli/node_modules/hexo-fs/node_modules/chokidar/node_modules/fsevents
gyp ERR! node -v v0.12.4
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm WARN optional dep failed, continuing fsevents@0.3.6
/usr/local/bin/hexo -> /usr/local/lib/node_modules/hexo-cli/bin/hexo
hexo-cli@0.1.7 /usr/local/lib/node_modules/hexo-cli
├── abbrev@1.0.7
├── minimist@1.1.1
├── bluebird@2.9.30
├── tildify@1.1.0 (os-homedir@1.0.0)
├── chalk@1.0.0 (escape-string-regexp@1.0.3, ansi-styles@2.0.1, supports-color@1.3.1, strip-ansi@2.0.1, has-ansi@1.0.3)
└── hexo-fs@0.1.3 (escape-string-regexp@1.0.3, graceful-fs@3.0.8, chokidar@0.12.6)

**Comment by sakz** [comment]
@Xuanwo i try this command   npm install hexo-deployer-git --save   but it did not work

hexo
{ [Error: Cannot find module './build/Release/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/default/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
{ [Error: Cannot find module './build/Debug/DTraceProviderBindings'] code: 'MODULE_NOT_FOUND' }
Usage: hexo <command>

**Comment by sakz** [comment]
$ npm install hexo --no-optional

I reinstall with the command above
It finally works!!!!!!

**Comment by sakz** [comment]
```$ npm install hexo --no-optional```

I reinstall with the command above
It finally works!!!!!!

**Comment by akring** [comment]
@sakz Great job man!Same problem and  same solution,this worked for me.

**Comment by zhuangxq** [comment]
@sakz Great job man!Same problem and same solution,this worked for me, too.

**Comment by felayman** [comment]
@sakz  i meet the same question with you. and use the same command npm install hexo --no-optional and it finally work

**Comment by PokimLee** [comment]
@sakz you are so coooool ! man

**Comment by WHaiLong** [comment]
@sakz  It worked for me, tks!

**Comment by cupools** [comment]
@sakz thanks!

**Comment by WangXiZhu** [comment]
hello, when i want to run hexo , the command line show

exo hexo
Usage: hexo <command>

Commands:
  clean     Removed generated files and cache.
  config    Get or set configurations.
  deploy    Deploy your website.
  generate  Generate static files.
  help      Get help on a command.
  init      Create a new Hexo folder.
  list      List the information of the site
  migrate   Migrate your site from other system to Hexo.
  new       Create a new post.
  publish   Moves a draft post from _drafts to _posts folder.
  render    Render files with renderer plugins.
  version   Display version information.

Global Options:
  --config  Specify config file instead of using _config.yml
  --cwd     Specify the CWD
  --debug   Display all verbose messages in the terminal
  --draft   Display draft posts
  --safe    Disable all plugins and scripts
  --silent  Hide output on console

For more help, you can use 'hexo help [command]' for the detailed information
or you can check the docs: http://hexo.io/docs/

i guess the hexo is successfly installed on my mac , but  the server does't work

**Comment by WangXiZhu** [comment]
oh, after i update hexo , the first problem is solved. but when i change the file '_config.yml' , the hexo server is not work!

**Comment by leesei** [comment]
@WangXiZhu please open new issue instead of commented on closed ones
post enough info for us to analyse the problem

**Comment by edagarli** [comment]
npm install hexo --no-optional

 “--no-optional"  why？

**Comment by edagarli** [comment]
justhacker:edagarli.github.io justhacker$ hexo
Usage: hexo <command>

Commands:
  clean     Removed generated files and cache.
  config    Get or set configurations.
  deploy    Deploy your website.
  generate  Generate static files.
  help      Get help on a command.
  init      Create a new Hexo folder.
  list      List the information of the site
  migrate   Migrate your site from other system to Hexo.
  new       Create a new post.
  publish   Moves a draft post from _drafts to _posts folder.
  render    Render files with renderer plugins.
  version   Display version information.

Global Options:
  --config  Specify config file instead of using _config.yml
  --cwd     Specify the CWD
  --debug   Display all verbose messages in the terminal
  --draft   Display draft posts
  --safe    Disable all plugins and scripts
  --silent  Hide output on console

**Comment by edagarli** [comment]
server command unrecognized

**Comment by leesei** [comment]
@edagarli Do read the documents:
https://hexo.io/docs/server.html#hexo-server
