### ISSUE TITLE
Same content on different pages/posts

### ISSUE THREAD

**Issue by ianpogi5** [hexojs/hexo#1532]
Any ideas how I could implement this?

I tried to add a partial code in a page but it was not processed and was spit out as is in the generated html.

For example in my theme layout/_partial folder, I have a file called content.ejs

``` content.ejs
<p>Some common content</p>
```

In source folder, I have a file called page1.html

``` page1.html
<h1>Title</h1>
<p>some text</p>
<%- partial('_partial/content') %>
<p>more text</p>
```

I expected this output:

``` page1.html
<h1>Title</h1>
<p>some text</p>
<p>Some common content</p>
<p>more text</p>
```

Instead I gout the output:

``` page1.html
<h1>Title</h1>
<p>some text</p>
<%- partial('_partial="" content')="" %="">
<p>more text</p>
</%->
```

Any other way I could do this?

**Comment by PhiLhoSoft** [comment]
Opinion from a novice: you try to put EJS tags in a .html file, I don't think it is processed by Hexo (perhaps it was in previous versions, I don't know).
EJS tags can be, AFAIK, only used in templates.
I understood that in v.3, Hexo uses Nunjucks templating in the posts, perhaps you can try this syntax instead of the EJS one?
