### ISSUE TITLE
Hexo API Question

### ISSUE THREAD

**Issue by wlaurance** [hexojs/hexo#1578]
The API seems to use the `hexo` executable behind the scenes.

I'm trying to convert large sites to static html. Combined there are a lot of posts > 10,000. The process seems slow going through the executable.

Is there anyway to keep this work inside the node process?

**Comment by wlaurance** [comment]
After further research I've seen that the processes always write to disk (as they should). I think I may try and speed up operations by having an in memory file system. Any ideas for this?

**Comment by Xuanwo** [comment]
@wlaurance  Nice try, If all the operations are in memory, the speed must be up.
And you can test the stablity of hexo in huge files. No one use Hexo to generate so huge site before.  Please share everything happened in generating, they must be useful!

**Comment by tomap** [comment]
You could either modify hexo (a lot, I believe), to keep stuff in memory (use stream/string in ram, instead of fs), or you could just use a ram disk. On linux, you can use tmpfs
See here to set it up: https://www.jamescoyle.net/how-to/943-create-a-ram-disk-in-linux
on windows, you can google "ram disk windows".

Does that answer your issue? Can we close this issue?

**Comment by stevenjoezhang** [comment]
Closing as answered.
