### ISSUE TITLE
It seems that hexo can't work well with MathJaX when meets "_"

### ISSUE THREAD

**Issue by veya2ztn** [hexojs/hexo#1889]
下述代码包含了利用MathJax在markdown中显示数学公式，包括行间的使用`$$ $$`和行内的使用`$ $`

``` markdown
### Mathtype in List
+ Transverse Ising model
  $$
  H=-\sum_{i=1}^N (\sigma_{i}^x \sigma_{i+1}^x+g \sigma_{i}^z)
  $$
###Mathtype between lines
$$
H=-\sum_{i=1}^N (\sigma_i^x \sigma_{i+1}^x+g \sigma_i^z)
$$
### Mathtype inline in list
+ the particle has only two state $\left| \uparrow \right\rangle$ and $\left| \downarrow \right\rangle$, which means that $\sigma^z \left| \uparrow \right\rangle =1 \left| \uparrow \right\rangle$
``` 
### Expected behavior (预期行为)

预期的行为应当是

![](http://7xseg9.com1.z0.glb.clouddn.com/16-4-13/42807939.jpg)
### Actual behavior (实际行为)

![](http://7xseg9.com1.z0.glb.clouddn.com/16-4-13/47478637.jpg)

### Guessing Reason (原因猜测)
我用了一下最新的hexo-math支持的KaTex
I use the KaTex for testing
``` markdown
{% math %}
\begin{aligned}
H=-\sum_{i=1}^N (\sigma_i^x \sigma_{i+1}^x+g \sigma_i^z)
\end{aligned}
{% endmath %}
```
是可以实现的,然后我把所有的“_”符号给删去，
And I find it works. And if I delete all the script `_` in LaTeX code
```markdown
  $$
  H=-\sum^N (c^x c^y+g c^z)
  $$
```
mathJaX 就可以渲染了，所以问题在于hexo 在渲染的时候会把一些`_`给丢去，导致mathjax无法识别
it now can work.
So the problem is that when the hexo change the ".md" into web file the text in ".md" changed and some notation like "_" lost

**Comment by familyld** [comment]
这个问题是由Hexo自带的Markdown渲染引擎和MathJax冲突引起的，解决方法很简单。更换Markdown渲染引擎就可以了。详细可以查看[我的博文](http://2wildkids.com/2016/10/06/%E5%A6%82%E4%BD%95%E5%A4%84%E7%90%86Hexo%E5%92%8CMathJax%E7%9A%84%E5%85%BC%E5%AE%B9%E9%97%AE%E9%A2%98/)。

This issue is caused by the conflict of hexo-renderer-marked(Hexo's default Markdown renderer) and MathJax. To fix this issue, you can simply change your markdown renderer. See the detail in [my blog](http://2wildkids.com/2016/10/06/%E5%A6%82%E4%BD%95%E5%A4%84%E7%90%86Hexo%E5%92%8CMathJax%E7%9A%84%E5%85%BC%E5%AE%B9%E9%97%AE%E9%A2%98/).

**Comment by asiagood** [comment]
当$$ $$ 内出现\begin{align} \end{align}的时候，公式渲染还是会出现问题，各种尝试目前无法解决。
