### ISSUE TITLE
Multiple users

### ISSUE THREAD

**Issue by ShavidzeT** [hexojs/hexo#1978]
Is there any plugin or way to register users on blog web-page.
So I need users management, they should add posts and I should manage these posts.
I have used hexo only once time for testing.
Any suggestions?

**Comment by carl0schen** [comment]
I think it is difficult. You can consider CMS, rather than static pages generator. Both systems user groups are not the same.

**Comment by ShavidzeT** [comment]
@carl0schen Yeap.
I think I need to build own plugin on hexo.
My blog doesn't have hard functionality but you know custom modules sometimes is more important that performance.

**Comment by lzjqsdd** [comment]
yes,it't hard.Hexo is a static blog,you can consider other dynamic with database such as wordpress.

But I have an idea but haven't try.Since Hexo is based on git and every one can pull request on your repo,you can set some permission in you repo,and deal with pull request to manage different posts.

**Comment by ShavidzeT** [comment]
@lzjqsdd I already have solution how to solve this problem on hexo. But I haven't time yet.
I'll enhance posts flexibility. :small_blue_diamond:
