### ISSUE TITLE
How to get prev next links by category?

### ISSUE THREAD

**Issue by agragregra** [hexojs/hexo#2177]
Prev, next links works for all posts in all categories. But how to make when prev next links generate per category, where placed the post?

**Comment by PirtleShell** [comment]
If I'm understanding your question, you want to know how you can get the pagination to cycle through _just a few_ specifically selected categories/tags instead of all of them?

[Hexo-pagination](https://github.com/hexojs/hexo-pagination) probably has some of the functionality you're looking for. It provides an easy way to generate arrays of pages with a given set of tags that you can cycle through in your templates and it can give you the prev/next links for a specific tag or set of tags.
