### ISSUE TITLE
Feature Request: Allow turning off watch() for files inside node_modules

### ISSUE THREAD

**Issue by xunnanxu** [hexojs/hexo#2179]
## Environment Info

Hexo version 3.2.2

Plugin version(`npm ls --depth 0`)

```
+-- hexo@3.2.2
+-- hexo-deployer-git@0.2.0
+-- hexo-generator-archive@0.1.4
+-- hexo-generator-category@0.1.3
+-- hexo-generator-feed@1.2.0
+-- hexo-generator-index@0.2.0
+-- hexo-generator-tag@0.2.0
+-- hexo-renderer-ejs@0.2.0
+-- hexo-renderer-marked@0.2.11
+-- hexo-renderer-stylus@0.3.1
+-- hexo-server@0.2.0
```
## Feature Request

Allow turning off watch() for files inside node_modules
## Use Case

Right now it's easy to get too many open files error. The main reason is node_modules often contributes a lot of files. While understanding sometimes this is useful when updating code, this is generally unnecessary. Users should be allowed to filter out certain directories to be watched.

**Comment by dotmagic** [comment]
I have exactly the same problem! It seems there was a fix commited some time ago:
https://github.com/hexojs/hexo/commit/4eaec8ac2219eacddb1222a1374543738e983c8f

However, its still broken for me. :(

**Comment by darekkay** [comment]
I've tried solving this problem with adding `node_modules` to `skip_render`, but unfortunatelly this doesn't make a difference :(

**Comment by SukkaW** [comment]
The feature seems to be added in #2631
The documents will update soon.

**Comment by seaoak** [comment]
I think #2631 does not resolve this issue.

#2631 is to exlude some dirs/files from visiting (=processing) only.

To prohibit Hexo from watching dirs/files,
the option `ignored` should be passed to `chokidar.watch()`.
(Not `ignore`)

The calling chain is:
1. `chokidar.watch()` is called by `watch()` of `hexo-fs` with its `options` parameter.
2. `watch()` of `hexo-fs` is called by `Box.prototype.watch()` with `this.options`.
3. `this.options` of `Box` is generated by the constructor of `Box`.

So, to resolve this issue, set the `options.ignored` of an instance of `Box`.

A patch (under development) for this issue was:
https://github.com/hexojs/hexo/compare/master...seaoak:feature/allow-turning-off-reading-and-watching-for-specified-directories

I will continue to update this patch.
