### ISSUE TITLE
多说倒闭了，建议修改下文档

### ISSUE THREAD

**Issue by Master-Wang** [hexojs/hexo#2466]
多说昨天发邮件宣布 2017.6.1 停止服务，建议及时更新下文档  http://dev.duoshuo.com/threads/58d1169ae293b89a20c57241

**Comment by Lizhooh** [comment]
看这：https://www.zhihu.com/question/57426274/answer/153065672

**Comment by AgentEric** [comment]
"Due to the adjustment, Duoshuo business very regret to announce more said the project will close.We will be in June 1, 2017 formally closing services, before that you can through the background data export function to export its own site review data.We very much regret the inconvenience caused to you, and thank you for your accompany all the way."

Hope Hexo help informing people to stop using Duoshuo Service。

**Comment by NoahDragon** [comment]
请问文档何处需要修改？
