### ISSUE TITLE
How can I place an Ad banner in the middle of the article?

### ISSUE THREAD

**Issue by amejiarosario** [hexojs/hexo#2513]
I could divide `<%- page.content %>` in half but then I would have incomplete HTML tags... Any better idea?

**Comment by NoahDragon** [comment]
I think the helper is what you are looking for. https://hexo.io/docs/helpers.html

You also could build your own helper. https://hexo.io/api/helper.html

**Comment by amejiarosario** [comment]
@NoahDragon I have look into the helpers but I don't think they help for this task

**Comment by mrttl** [comment]
Maybe worth trying:
[https://github.com/PirtleShell/hexo-include](url)
[https://github.com/kulikala/hexo-helper-partial-page](url)

Maybe have a link to your banner ad in the frontmatter?

**Comment by amejiarosario** [comment]
thanks @mrttl for your suggestions. What I'm looking is something like this:

```html
<%- first_half(page.content) %>
<%- partial('_ads/banner') %>
<%- second_half(page.content) %>
```

`first_half` will render the first half of the article and then `second_half` the reminder. It cannot be done just counting the number of characters and splitting on the midpoint. Otherwise, you could split a <p> tag and then in the other half contain the </p>...

**Comment by mrttl** [comment]
@amejiarosario  no problems, to be honest, I am not a fan of markdown at all. Being a designer Markdown gives little or no customization possibilities, so styling a Markdown post the way I want it never works. 

What I tried was having my posts set to HTML and not Markdown in the _config and in my scaffolds folder, you can still have front matter variables like you have with Markdown but now you can style and add what you want since it's HTML.

Also note, you can have HTML in front matter too if you want, so you can create two variables, and add the HTML in each front matter variable and then in your post.ejs you can output it.

Today was a long day, so not sure I made any sense... :D let me know if I can help you further.
