### ISSUE TITLE
unknown block tag: aplayer

### ISSUE THREAD

**Issue by Maybrittnelson** [hexojs/hexo#2573]
## Environment Info

Node version(`node -v`):

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`):

**Comment by NoahDragon** [comment]
Please lock the version to hexo 3.2.2. I think this issue related to the latest change https://github.com/hexojs/hexo/pull/2568  https://github.com/hexojs/hexo/pull/2461 , but still under investigating. 

Vuejs site also occurs the similar issue: https://github.com/vuejs/vuejs.org/issues/895

**Comment by seaoak** [comment]
Progress brief:

1. This issue is a bit difference from others (#2563 and vuejs/vuejs.org#895) because `aplayer` tag is not a "block" tag.  My understanding was that, by the latent bug, a non-block tag might be either correctly rendered or still a raw text.  But it was wrong.  So I should find another story.

2. About an HTML source code generated from Markdown, I believed that a `<pre>` element always took a `<code>` element as only immediate child.  But it is not true in Hexo.  So I should know the reason why original version of `lib/extend/tag.js` escaped only such a string (`<pre><code>...</code></pre>`).  Although I think that a `<pre>` element around a `<code>` element can be ignored (only `<code>` element will be escaped), I can not decide without the reason.

The investigation may take a while.  :sweat:

**Comment by NoahDragon** [comment]
@seaoak Thank for the clarification. It's a promising start. I could assist you to investigate the issue.

**Comment by NoahDragon** [comment]
@Maybrittnelson  Please get the latest version 3.3.7 and have a try.
