### ISSUE TITLE
The tag fancybox on line 77 in themes/landscape/README.md is not a recognized Liquid tag

### ISSUE THREAD

**Issue by DasBeste** [hexojs/hexo#2590]
I am a fresh man to hexo. While I am trying to make a deployment to github.My github pages throws a Exception Says "The tag fancybox on line 77 in themes/landscape/README.md is not a recognized Liquid tag".

node.js version -  6.10.3
hexo version - 3.3.7

**Comment by mylvcs** [comment]
Same Question. 
How did you solve it ?
Please tell me ,thx !

**Comment by mylvcs** [comment]
Update : I just deleted the README.md and my problem has been solved.
I'm totally fresh to this, so I don't know how to do, just want to solve it.
Anyway, now it's done. LOL

**Comment by i6020345** [comment]
i just deleted the /themes/landscape/README.md too
my problem has been soldved!!!!! thx @mylvcs

**Comment by lifecoderua** [comment]
Just got this, changed the Readme, re-publish and the github pages are all broken, with a warning on an incorrect build from GitHub.

It looks like git-publish sometimes go wild and publish the source branch instead of the gh-pages generated branch.

`rm -rf .deploy_git` and re-deploy solved this for me.

**Comment by jacoblin214** [comment]
@lifecoderua thank you! I solved this by rm -rf .deploy_git.
