### ISSUE TITLE
Is there a way to get url of post  when writing in markdown? and how?

### ISSUE THREAD

**Issue by xxxspy** [hexojs/hexo#2605]
Thanks for your reply.

**Comment by NoahDragon** [comment]
How about the url-for? https://hexo.io/docs/helpers.html#url-for

**Comment by seaoak** [comment]
I think the helper `url_for()` is for Hexo theme files (such as EJS files), not for markdown.

In markdown, you can use the `post_link` tag plugin to make a link for a post (even if the post is current post itself).   
https://hexo.io/docs/tag-plugins.html#Include-Posts

Example:

```hello-world.md
Link to this post: {% post_link hello-world %}
```

NOTE: the hyperlink `href="./"` is not proper way to link the current post because it will refer the root page at index pages.

If you need a *FULL* URL (not a URL fragment such as a PATH generated by above plugin), you need a tag plugin.

Previously, no such tag plugin was found.  So I made a simple tag plugin script for this purpose.  If you like, please taste my script as follows:

1. Download `post_permalink.js` from my Gist:   
   https://gist.github.com/seaoak/57886a2e91b5d31ffb5d0fe01fe21c74

2. Copy the file into `scripts` directory of your Hexo home directory:   
   `$ test -d ~/hexo/site/scripts || mkdir ~/hexo/site/scripts; cp -p post_permalink.js ~/hexo/site/scripts/`

3. Use this plugin in markdown:   
   `URL of this post: {% post_permalink %}`   
   or   
   `URL of original post: {% post_permalink slug-of-original-post %}`

For more information about "script", please refer the Hexo document:   
https://hexo.io/docs/plugins.html#Script

**Comment by NoahDragon** [comment]
@seaoak Haven't seen you for a while.

Thanks for the clarification. I totally misunderstood the question.
