### ISSUE TITLE
hexo 能否做到 增量 generate

### ISSUE THREAD

**Issue by tl3shi** [hexojs/hexo#2719]
每次 generate 的时候, check 一下与上次generated的结果? 比如
- 如果涉及到theme都变动当然得全量重新generated, 
- 如果仅仅是新增了一篇文章, 是不是只需要update 相应的tag, 索引之类的页面?  与之前不相关的posts是不是不用重新generated了?

**Comment by tl3shi** [comment]
还是说本身已经有这个功能而我孤陋寡闻了?

**Comment by JLHwung** [comment]
> 如果涉及到theme都变动当然得全量重新generated,

Hexo does not watch theme changes, if you revise the theme by hand, please run `hexo clean` first.

> 如果仅仅是新增了一篇文章, 是不是只需要update 相应的tag, 索引之类的页面? 

Hexo update tags/categories on any new posts. However, since tags/categories page is paginated, mostly hexo will re-generate *all* pages of *updated* tags/categories.

> 与之前不相关的posts是不是不用重新generated了?

Hexo will not re-generate unmodified posts.
