### ISSUE TITLE
Limit meta description to 160 characters 

### ISSUE THREAD

**Issue by RandallKent** [hexojs/hexo#2809]
## Feature request

Per [Moz](https://moz.com/learn/seo/meta-description), meta descriptions should be shorter than the 160-character limit.

**Comment by jbreckmckye** [comment]
Perhaps it's better to warn than to emit an error?

**Comment by AWulkan** [comment]
Please revert this change, you misunderstood how SEO works.

There are **no SEO benefits** what so ever by cutting off a descriptive text. The only reason why they **recommend** keeping it under 160 characters is because some search engines will truncate the text FOR YOU. That's why you need to get your message across in the description in under 160 character to entice users to click on your link in the search results. Cutting of the description text has **no benefits**.

The only thing you're doing is messing up the description by removing content from it. So if another service wants to show your full description, it will be cut off and incomplete. This will potentially have **negative** effects on your site traffic from other sources than main search engines.

Also just because some search engines don't display more than 160 characters doesn't mean that other search engines won't. It also doesn't mean that the descriptions are not used for other things like gauging what your content is about.

**Comment by jbreckmckye** [comment]
@AWulkan I thought this when I saw the PR go through, but decided I couldn't be bothered to kick this particular can down the road. You're absolutely right, though. People misunderstand search engine advice and treat Google's friendly suggestions with superstitious fear.

Google is not going to penalize you for having 200 character meta descriptions, because that _flies in the face of Google's own interests_. Google has nothing to gain by disqualifying content that is otherwise perfectly relevant to a user's search. All this woo and rumor fundamentally misunderstands the roles and objectives of search engines.

**Comment by AWulkan** [comment]
@jbreckmckye Indeed. I'm thinking about submitting a PR to revert this change, but right now I'm pretty busy. Maybe I'll do it sometime in the future before I start using Hexo again, if no one else beat me to it.

Right now all Hexo websites have incomplete description tags because of this change, which is pretty terrible.

Also, I realised this was just the issue, I will post in the pull request as well.

**Comment by NoahDragon** [comment]
@AWulkan Thanks for pointing this out. I'm not an expert on SEO, but I think you are right. We shouldn't force to truncate the description length, users should decide how to use the meta tag, someone may don't need SEO at all.

Here is a quote I think it is better explained how to use the meta description (from https://moz.com/learn/seo/meta-description):
> Meta descriptions can be any length, but search engines generally truncate snippets longer than 160 characters. **It's best to keep meta descriptions long enough that they're sufficiently descriptive**, but shorter than the 160-character limit.

I'm going to revert the change, please feel free to continue discussing in this thread if have any concerns.
