### ISSUE TITLE
Why can hexo create draft from only draft.md?

### ISSUE THREAD

**Issue by elleonard** [hexojs/hexo#2853]
## For question

I'd like to create draft by various scaffolds.
e.g)
hexo new draft_sports 2017-11-18-sports --draft
hexo new draft_book 2017-11-18-book --draft

but it seems to be not supported these commands...
How can I create draft by other scaffolds?

Is using shellscript and copying from another md to draft.md the best way?

**Comment by MegaJ** [comment]
I'm unfamiliar with those options. The [docs](https://hexo.io/docs/writing.html#Drafts) mention `hexo new [layout] title`. 

The `--draft` option is for enabling rendering for your drafts for example when you run 
`$ hexo server --draft`

Because of limitations from this code, hexo doesn't give you those options.
https://github.com/hexojs/hexo/blob/master/lib/plugins/filter/new_post_path.js#L49

I think you can use hexo to help you out actually, by registering a filter to override the defaults. But it seems much easier to write a simple shell script and have it handy in your path, or defined in your shell startup script.

Rather than overwriting your draft.md, it's probably simpler to move the newly created file.

**Comment by NoahDragon** [comment]
As @MegaJ states, you coulde run `hexo new draft title` to create a draft post.
