### ISSUE TITLE
How can I get the link of page and hope it start with "https"?

### ISSUE THREAD

**Issue by 2ue** [hexojs/hexo#2860]
## Environment Info
platform: win10 64
Node version(`node -v`):  8.6.0

## For question

I want to get he link of page and hope it start with "https"? the "page.permalink" can't do it;

**Comment by MegaJ** [comment]
I might not understand your use case, but from my point of view, it's unnecessary to get the `https` to show up. Using hexo probably means you're trying to build a static site. Static sites don't have much of a backend (unless you're using some third party server to do analytics, store comments, etc, but even then you don't control your data), and you won't have things like logins.

https means you're using SSL, which is crucial to keeping user information secure. But the thing is, if you have a static site readers don't provide you with personally identifiable information through your website. Since they don't provide you with sensitive information, is there any reason to make your site https?
