### ISSUE TITLE
Can not install hexo in Win8

### ISSUE THREAD

**Issue by Mabinogiysk** [hexojs/hexo#2870]
Node version(`node -v`): v8.9.1
PowerShell version: v4.0

I want to install hexo with PowerShell in Win8.1. It always stop at some point:
![image](https://user-images.githubusercontent.com/12441989/33163401-553d110c-d069-11e7-9a1a-8e3d6a1fe34f.png)
I have also tried with administrator permission and it didn't work.

**Comment by Mabinogiysk** [comment]
I have installed it with node.js v7.7 successfully and it failed with node.js v8.9.
Someone else reported this [problem](https://github.com/hexojs/hexo-cli/issues/23)

**Comment by demurgos** [comment]
Hi,
This is odd: `hexo-cli` does not have a postinstall step:
https://github.com/hexojs/hexo-cli/blob/89145a54c2737e314395afee13eeab3288a117fd/package.json#L9

The issue you linked to was caused by the transitive dependency `hexo-util`. Can you check which version of `hexo-util` was installed? Are you using a special registry/cache?

Could  you upload a [Gist](https://gist.github.com/) of your npm logs if available?

**Comment by hope320** [comment]
same question, have you got the solution? thanks!

**Comment by demurgos** [comment]
@hope320 
Could you try to install hexo using _yarn_ instead of _npm_?
Do you have any error logs? Could you paste them to Gist and give us the link?
What are your versions of npm and node?

I don't have a Windows computer. I tried to reproduce it with a windows 7 virtual machine but did not get the error. Any help to figure out the issue would be welcome.
