### ISSUE TITLE
[question] Is it possible to create a plugin to uses megadraft.io editor (medium like)?

### ISSUE THREAD

**Issue by lakano** [hexojs/hexo#2942]
Hi !

We've not yet used Hexo, we search a self-hosted blog in ReactJS to permit to include the awesome editor http://megadraft.io

We would like to known if your plugin system permit to do that. We've found a megadraft plugin that permit to translate the megadraft content to markdown ( https://www.npmjs.com/package/megadraft-js-export-markdown ), but we've seen in the #2936 ticket there is only one rendering system.

We can try to make a plugin, but we need to be sure it's possible with your system.

Regards,

**Comment by unnamed42** [comment]
If you can translate your content into some **static** renderable text then you can do it.
Indeed hexo can only have one *working* renderer, but it does not mean hexo has only one available renderer. There are quite a lot at https://hexo.io/plugins/, like [pandoc renderer](https://github.com/wzpan/hexo-renderer-pandoc), [ascii doc renderer](https://github.com/hcoona/hexo-renderer-asciidoc), [rst renderer](https://gitlab.com/mcepl/hexo-renderer-restructuredtext.git)
As an alternative, you can wrap your content in a tag so can be rendered through tag plugin system rather than renderer system, but the syntax looks slightly ugly. This reference may be helpful: https://hexo.io/api/tag.html 
I'm not a maintainer by the way, I'm just a user.
