### ISSUE TITLE
build page html always have � 亂碼

### ISSUE THREAD

**Issue by Ianpig** [hexojs/hexo#3014]
## Environment Info
https://ianchuu.com/2017/12/16/arrayhandle/
Node version(`node -v`):
v8.7.0
Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`): 

## For BUG

build page html always have � 亂碼

when i use windows 7  and linux, it's will appear.

**Comment by NoahDragon** [comment]
Could you please elaborate?

**Comment by tcrowe** [comment]
I couldn't find "亂碼" or "� 亂碼" in the page you linked.

Sometimes a BOM interferes with the file encoding:
https://en.wikipedia.org/wiki/Byte_order_mark

In your editor and source control you can configure it to automatically detect or use a specific encoding. It should usually be UTF-8, unix line endings, without BOM. (if possible)

Otherwise if that can't be done on Windows and you copy the files from others systems weird characters will show up at the start.

Can you let me know if that clears up the issue, @Ianpig
