### ISSUE TITLE
[Feature Request] Allow url_for to have multiple parameters and build the url with them.

### ISSUE THREAD

**Issue by michaeljota** [hexojs/hexo#3047]
## Environment Info

Node version(`node -v`): 8.9.4

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`): 
```
+-- hexo@3.5.0
+-- hexo-deployer-git@0.3.1
+-- hexo-generator-archive@0.1.5
+-- hexo-generator-category@0.1.3
+-- hexo-generator-feed@1.2.2
+-- hexo-generator-index@0.2.1
+-- hexo-generator-tag@0.2.0
+-- hexo-migrator-rss@0.1.4
+-- hexo-renderer-ejs@0.3.1
+-- hexo-renderer-marked@0.3.2
+-- hexo-renderer-scss@1.1.0
`-- hexo-server@0.2.2
```

## For feature request

Currently url_for only accepts one argument, ignoring any other you may pass.
```js
// in a for loop, where i is the looped variable.
url_for('page', i); // <-- i is ignored, and all the urls points to www.ablog.com/page
// workaround
 url_for(`page/${i}/`) <-- urls point to a numbered page (www.ablog.com/page/[1, 2, ..., n])
```

I would be nice if you could pass an indeterminate number of arguments, and the function resolves all the arguments.
```js
// in a for loop, where i is the looped variable.
url_for('page', i); // <-- urls should point to a numbered page (www.ablog.com/page/[1, 2, ..., n])
```

**Comment by JLHwung** [comment]
I am not positive on this feature as it has an obvious workaround:
```js
url_for(['page', i].join("/"))
```
Anyway, any feedbacks are welcome.

**Comment by Aofzazgithub** [comment]
AofzazGithub

**Comment by NoahDragon** [comment]
Agree with @JLHwung , work around should be fine.

**Comment by michaeljota** [comment]
I don't feel that way. If you have to say workaround, then it is not a solution.

**Comment by demurgos** [comment]
The larger issue here is that you want to map an application state to a URL. This is not a trivial operation and is outside of the scope of path resolution. This requires knowledge about how the URLs of your website are structured.

Your choice it to treat each of the components of your state as a string and use them as individual segment of the URL path. What if someone want to use query parameters, fragments or wants concatenate a few values in the same segment of the URL path?

If all you want is to join path segments and resolve the URL, then simply compose the existing functions as suggested above.

As a nit, joining on forward slashes does not properly escape special characters. Joining path segments should be done with the dedicated function `require("path").posix.join`. This is also better semantically: it helps to communicate the intent of the operation.
```js
url_for(path.posix.join("page", i.toString(10)))
```

Ultimately, if you want a more complex behavior, the best solution is to write your own function.

Closing the issue since the request is rejected, you can still comment if you want to argue for it.
