### ISSUE TITLE
Cannot display show markdown code source

### ISSUE THREAD

**Issue by Cat7373** [hexojs/hexo#3185]
## Environment Info

Node version(`node -v`):
```sh
Cat73-MacBook-Air:~ Cat73$ node -v && $(which npm) -v
v9.3.0
6.0.1
```

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`): 
```
Hexo 3.7.1
```

## For BUG
https://github.com/theme-next/hexo-theme-next/issues/309

### Expected behavior 
Like GitLab:

Source: 

![](https://user-images.githubusercontent.com/9296576/40756891-5acfad30-64b8-11e8-9d88-a878797cdbd1.png)

Render:

![](https://user-images.githubusercontent.com/9296576/40756893-5d2aa63e-64b8-11e8-9f84-7f96f0ffcd65.png)

### Actual behavior 
Source:
 
![](https://user-images.githubusercontent.com/9296576/40756978-c501ceae-64b8-11e8-8e94-fc107733babe.png)

Render:

![](https://user-images.githubusercontent.com/9296576/40756981-c984b612-64b8-11e8-8163-e488c913272f.png)

**Comment by demurgos** [comment]
It is not clear what you want to achieve. If you actually want to avoid the raw markdown and render the code block, do not indent it so much. Fenced code blocks should be indented at the same level as their container.

Closing since it's not an Hexo issue. Feel free to use this issue to discuss it further.
