### ISSUE TITLE
mathjax bug on chrome and firefox

### ISSUE THREAD

**Issue by Freyr-Wings** [hexojs/hexo#3279]
## For BUG

I don't know if it is a bug or just the error with my configuration, the equation of my blog shows blank box after it has been rendered(it even looks better in the preview now), but the equation can show properly on Microsoft Edge
my page is https://freyr-wings.github.io/2018/10/09/%E5%9B%BE%E4%B8%8E%E8%8A%82%E7%82%B9%E7%9A%84%E8%A1%A8%E8%BE%BE%E5%AD%A6%E4%B9%A0/

I installed kramed and slightly modify inline.js
  escape: /^\\([`*\[\]()#$+\-.!_>])/,
  em: /^\*((?:\*\*|[\s\S])+?)\*(?!\*)/,
it works a few months ago

I have done a lot of search but still cannot fix this error.
Thanks!

**Comment by YoshinoriN** [comment]
@Freyr-Wings 

I checked your site using by Chrome. A mathjax font are blocked by CORS policy.
You can see error message using by browser developer tool (I used chrome dev tool.)

Please try to change CDN to [official recommended CDN](https://docs.mathjax.org/en/latest/start.html).
I think this problem caused by redirect `bootcss` CDN to `cloudflare` CDN.

**Comment by Freyr-Wings** [comment]
Wow, it did work! Thanks a lot
To summarize, just change _config.yml
mathjax:
  cdn: //cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML
