### ISSUE TITLE
Hexo Math formula could not display in the right way

### ISSUE THREAD

**Issue by congchan** [hexojs/hexo#3280]
## Environment Info

Node version(`node -v`): v6.0.0

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`): 
+-- hexo@3.7.1
+-- hexo-deployer-git@0.3.1
+-- hexo-generator-archive@0.1.5
+-- hexo-generator-baidu-sitemap@0.1.5
+-- hexo-generator-category@0.1.3
+-- hexo-generator-feed@1.2.2
+-- hexo-generator-index@0.2.1
+-- hexo-generator-searchdb@1.0.8
+-- hexo-generator-seo-friendly-sitemap@0.0.21
+-- hexo-generator-sitemap@1.2.0
+-- hexo-generator-tag@0.2.0
+-- hexo-inject@1.0.0
+-- hexo-math@3.0.4
+-- hexo-renderer-ejs@0.3.1
+-- hexo-renderer-marked@0.3.2
+-- hexo-renderer-stylus@0.3.3
+-- hexo-server@0.2.2
+-- hexo-symbols-count-time@0.4.4
+-- hexo-wordcount@3.0.2
`-- save@2.3.2

## For BUG
Hi, previously there is no such issue, for old pages which were once fine now becomes buggy. Thanks.

1. BUG description
The Math formula seems ok when the pages are loading, however after loading completed, it turns out to be a mess, all the digits displayed as squares. 
http://shukebeta.me/UoE-st/#System-Reliability
2. The way to reproduce
Open the link, wait and see the formula crahes

**Comment by YoshinoriN** [comment]
Same as #3279 

@congchan 

I checked your site using by Chrome. A mathjax font are blocked by CORS policy.
You can see error message using by browser developer tool (I used chrome dev tool.)

Please try to change CDN to [official recommended CDN](https://docs.mathjax.org/en/latest/start.html).
I think this problem caused by redirect `bootcss` CDN to `cloudflare` CDN.
