### ISSUE TITLE
Render a part of hexo with existing ExpressJS server and EJS

### ISSUE THREAD

**Issue by NLDev** [hexojs/hexo#3414]
Good Day!

Basically I wanted to ask, whether it's possible to render just a part of a hexo template with my existing ExpressJS server and EJS. 

Say I have a route `/blog`
```JS
app.get("/blog", (req, res) => {
    res.render("blog", {
        "route": req.path,
    });
});
```

and an EJS template `blog.ejs`. 
Now I want to include a part of hexo in this `blog.ejs` file like so:

```HTML
<%- include("global/header"); -%>
    <div class="main-content">
        <% /* I want to include the blog part of hexo without header/footer here */ %>                            
    </div>
<%- include("global/footer"); -%>
```

Is that possible?

**Comment by momocow** [comment]
[Hexo Rendering API](https://hexo.io/api/rendering) is what you need.

Before calling `res.render`, use the Hexo rendering API to render the blog and then pass the result to [`locals` parameter](http://expressjs.com/zh-tw/api.html#res.render).

To exclude header or footer, customizing templates in your Hexo theme can achieve this.
[Check out this page for more info about Hexo templates.](https://hexo.io/docs/templates)

---

I think there is another way worth trying to render the Hexo blog under route `/blog`.

By [Hexo router API](https://hexo.io/api/router#Get-a-Path), you can make use of the goodness of [NodeJS Stream API](https://nodejs.org/api/stream.html) like the following example code.

Since `hexo.route.get()` returns a Readable, you can pipe it to the [express `res` object](http://expressjs.com/zh-tw/api.html#res), which is a Writable.
`pipe` method will end the response for you by default.

```js
app.get("/blog", (req, res) => {
    hexo.route.get(req.path).pipe(res);
});
```

After delegating the rendering job to Hexo, include your `blog.ejs` as a part of customized templates in your Hexo theme.

It just another information for you. Not testing it myself, but it seems feasible and pretty enough!

**Comment by NLDev** [comment]
Thank you very much! :)
