### ISSUE TITLE
hexo启动后，如何后台运行？

### ISSUE THREAD

**Issue by flyup510** [hexojs/hexo#3709]
hexo启动后，启动界面不能做任何事情。
远程连接软件关掉后，hexo服务也会关掉。

**Comment by PingAnNetBar** [comment]
我暂且把你说的`界面`理解成页面吧。据我所知，hexo是一个静态网页。可以说没有`后台`这个东西，后台是自动化的帮助用户完成任务。 但hexo功能都是你在底层配置文章配置相关参数完成的，甚至是创建一篇文章都是通过命令行完成的，也没有相关GUI来帮助完成。   如果想拥有的是走到哪里使用任何一台终端都可以登录并完成相关操作的`动态博客`。我推荐`WordPress`

**Comment by stevenjoezhang** [comment]
`screen`

**Comment by curbengh** [comment]
I assume 后台 means a CMS or an admin like ? With assumption, previous comment is right about Hexo generate _static_ page, meaning the web page is pre-generated, rather than generated on-the-fly like Wordpress (1). 

Hence, Hexo is a [static site generator](https://www.staticgen.com/) (SSG). There is no database (no mysql, no phpmyadmin) to install or configure, the web server doesn't execute things (no php, no cgi, no php engine) and simply functions as a file server.

If you need a CMS in Hexo, you can try [hexo-admin](https://github.com/jaredly/hexo-admin) or [Forestry.io](https://forestry.io/). There are more, I'm just giving example.

(1): Note Wordpress can be transformed into an SSG through [plugin](https://github.com/WP2Static/wp2static), but it's not an SSG itself.

**Comment by RainVector** [comment]
在MINGW64里面可以使用下面的命令：
```bash
hexo s &
```
其中`&`就是后台运行的符号

**Comment by curbengh** [comment]
> 远程连接软件关掉后，hexo服务也会关掉

I assume 远程连接软件 means something like ssh? seems like you want to run hexo server in the background?

In my local testing (Ubuntu): Neither `hexo s &` nor `nohup hexo s &` works for me.

The following works for me:
``` bash
$ hexo s &
$ disown -h %1
```

The above assumes `hexo` is the only jobs. If there are multiple jobs, you might want to `disown` just the hexo.

``` bash
$ hexo s &
$ jobs
[1]  Running                 ping
[2]+  Running                hexo s &
$ disown -h %2
```

**Comment by lybtt** [comment]
直接hexo g生成静态页面文件夹public，然后使用相关的静态网站托管服务部署就好了，github page 或者什么对象存储。或者安装相应的插件，hexo g -d 直接部署。
并不需要一直在服务器后台运行。

**Comment by curbengh** [comment]
It depends on the use case; personally, I wouldn't run `hexo s` on production (public website) environment, I would at least reverse proxy it behind _battle-tested_ servers like Apache/Nginx/Caddy.

For an internal website, `hexo s` offers a quick and easy setup (well, there is no setup, just run), compared to the aforementioned web servers.
