### ISSUE TITLE
写的 <%- is_home() %> 在首页(index) 返回 false ???

### ISSUE THREAD

**Issue by zhwangart** [hexojs/hexo#3738]
写 `<%- is_home() %>` 在 `http://localhost:4000/` 返回 **true** ，然后生成（`$ hexo g`）文件中的 index.html 中，则显示 **false** ？？？
在 `$ hexo g` 之前已经多次执行 `$ hexo clean`

**Comment by zhwangart** [comment]
我找到问题原因了，是因为 `<%- partial('_partial/header', null, {cache: !config.relative_link}) %>`中的`null, {cache: !config.relative_link}`导致，如果删除 `null`就好了，请问这个 `null` 具体起什么作用？？？我是从默认主题中复制过来的！

**Comment by stevenjoezhang** [comment]
其实这并不是`null`的问题，正确的做法是删除`{cache: !config.relative_link}`。你可以看下文档，`partial`是用于缓存的，遇到`is_home`这种在每个页面上不同的方法就出问题了。

**Comment by stevenjoezhang** [comment]
Duplicate of #3483

**Comment by zhwangart** [comment]
> Duplicate of #3483

请问下为什么 `is_home` 会遇上 `cache`  就出问题呢？

**Comment by stevenjoezhang** [comment]
可以这样理解：执行`hexo g`，Hexo开始渲染第一个页面（可能并不是index），此页面中`is_home()`为`false`。然后，Hexo开始渲染第二个、第三个页面。由于开启了`cache`，Hexo不会重新执行`is_home()`方法，而是直接套用第一个页面的结果（即返回`false`，并没有重新渲染）。这就导致了问题。
`hexo s`的机制又与`hexo g`不同，因此更加令人感到困惑。

**Comment by zhwangart** [comment]
@stevenjoezhang 非常感谢，让我这么笨的人都理解了这么难的关系...

**Comment by stevenjoezhang** [comment]
这个选项确实还不够智能（可能就是这么设计的？）毕竟如果能够根据页面类型进行缓存，就可以避免你说的这个问题。

**Comment by SukkaW** [comment]
@ppoffice has implement a smart `_partial()` helper with fragment cache automatically enabled: https://github.com/ppoffice/hexo-theme-icarus/blob/master/includes/helpers/override.js#L158-L187

@zhwangart @stevenjoezhang

**Comment by ppoffice** [comment]
> 
> 
> @ppoffice has implement a smart `_partial()` helper with fragment cache automatically enabled: https://github.com/ppoffice/hexo-theme-icarus/blob/master/includes/helpers/override.js#L158-L187
> 
> The side-effect is huge memory usage since all partials will be cached in memory.
> 
> @zhwangart @stevenjoezhang

Actually, the memory size of the cache object is negligible, event with the `_partial()` helper I wrote. I took a snapshot of the heap when rendering https://github.com/jiangtj-lab/hexo-many-posts with `hexo-theme-icarus`:

<img width="819" alt="Annotation 2019-12-20 170806" src="https://user-images.githubusercontent.com/8849362/71295952-f77e7280-234b-11ea-89ba-f834e638785c.png">

The `cache` object in [lib/plugins/helper/fragment_cache.js#L4](https://github.com/hexojs/hexo/blob/4.1.1/lib/plugins/helper/fragment_cache.js#L4) only takes up **3.0MB** with **1418** HTML fragments. I also found out that most of the memory is consumed by the unreleased `CacheStream` in [/lib/plugins/console/generate.js#L48](https://github.com/hexojs/hexo/blob/4.1.1/lib/plugins/console/generate.js#L48). Thus, my suggestions to reduce the memory size of Hexo are

- Use the `concurrency` option when `hexo g` https://github.com/hexojs/hexo/pull/3665
- Simplify the HTML structure of your theme so that the rendered HTML fragments are small

**Comment by stevenjoezhang** [comment]
I'm closing this issue. Please join the discussion in https://github.com/hexojs/hexo/issues/2451
