### ISSUE TITLE
Milan 这个主题并不能提供使用为什么还要放在主题列表？

### ISSUE THREAD

**Issue by zhwangart** [hexojs/hexo#3817]
Milan 这个主题并不能提供使用为什么还要放在主题列表？
并且访问还被浏览器警告：面临潜在的安全风险
> Firefox Developer Edition 检测到潜在的安全威胁，因此没有继续访问 gumroad.com。若您访问此网站，攻击者可能会尝试窃取您的密码、电子邮件、信用卡等信息。

https://gumroad.com/l/hexo-theme-milan

**Comment by SukkaW** [comment]
Although most of Hexo's theme is open-sourced and free to use, but not all of them.

According to the milan's website, you have to pay for more than 20 USD to get the theme since it is for e-commerce. Many WordPress themes are not free, it is fair enough to have a non-free Hexo theme, right?

Even Google Chrome has no security notice when visiting this website. ONLY the Mozilla Firefox does this. Evil Mozilla, right?

**Comment by zhwangart** [comment]
Oh, I am very sorry about this.
