### ISSUE TITLE
文章URL的处理

### ISSUE THREAD

**Issue by xudadi** [hexojs/hexo#3842]
目前hexo的文章都是以文件夹的形式存放，能否优化为以.html结尾处理

**Comment by SukkaW** [comment]
It is quite simple. You just need to modify a little bit of your configuration file.

Try this:

```yaml
permalink: :year/:month/:day/:title.html
```

**Comment by xudadi** [comment]
@SukkaW 虽然这样在浏览器上是这样显示的链接，但是文件还是这样存放的，例如：
https://abc.com/20191109-test1/index.html
https://abc.com/20191109-test2/index.html
https://abc.com/20191109-test3/index.html
浏览器是上面这样显示的

但是文件夹却是这样存放的
![image](https://user-images.githubusercontent.com/12946857/68526120-8642ad00-0313-11ea-9749-a9e4ee9bb294.png)

我想的是直接生成html文件

**Comment by SukkaW** [comment]
It doesn't matter how you store your posts. Unless your markdown files doesn't located in `_post` directory or you add `permalink` option to front-matter of your markdown file, otherwise hexo will always render and generate based on `permalink` configuration defined in your `_config.yml`.

If you want something like `https://example.com/2019-11-09-something.html`, you should change your config to this:

```yaml
permalink: :year-:month-:day-:title.html
```

**Comment by xudadi** [comment]
ok,非常感谢
