### ISSUE TITLE
'ignore:' option doesn't work on invidual file

### ISSUE THREAD

**Issue by curbengh** [hexojs/hexo#3873]
1. Create more than one dummy files in `source/foo/` folder
2. Configure `ignore:`,

``` yml
_config.yml
ignore:
  - '**/foo/dummy1.txt'
```

### Expected behavior

`public/foo/dummy1.txt` should not exist

### Actual behavior

`public/foo/dummy1.txt` is there

### Workaround

Use `exclude:`, but it doesn't work in `themes/` folder.

---

`ignore` currently works on folder level only,

``` yml
_config.yml
ignore:
  - '**/foo'
```

Noticed this limitation while working on https://github.com/hexojs/hexo-generator-feed/pull/110.

I haven't dive into source code for this issue yet, @seaoak can you help?

**Comment by seaoak** [comment]
I'm afraid I owe you an apology.
I was conscious this restriction when I made the PR #3797.
I understood it is intentional, but not documented yet.

This restriction is caused by the current implementation of `lib/box/index.js`.
In the definition of `Box.prototype._readDir`, all non-directory entries in a directory are returned unconditionally.

On the other hand, `ignored:` option of "chokidar" already supports individual files.
That is, the PR #3797 works well for individual files.
https://www.npmjs.com/package/chokidar

I understand that there are use cases such as files under `themes/` folder.

I try to make a patch to improve `lib/box/index.js`.

**Comment by curbengh** [comment]
https://github.com/hexojs/hexo/pull/3878
