### ISSUE TITLE
tags and categories are case sensitive 

### ISSUE THREAD

**Issue by RobotWuYun** [hexojs/hexo#3875]
when I push my blog to github,and open the blog,I find some articles are not as a true number is the page number,and the tag is not like it as tags page
for example:
![tags.jpg](https://i.loli.net/2019/11/19/QkytXS9GaFIodWx.jpg)
![articles for tags page.jpg](https://i.loli.net/2019/11/19/7RwUhbHXcPlIOep.jpg)

and 

this is my give a method to the problem
[the article path](https://robotwuyun.github.io/2019/08/19/%E8%B8%A9%E5%9D%91%E6%8C%87%E5%8D%97_Hexo_1/)

**Comment by curbengh** [comment]
https://github.com/hexojs/hexo/blob/a58acb9ca0a62f58eb6f0f751f001c0e984849db/lib/models/tag.js#L22

Read [`config.filename_case`](https://hexo.io/docs/configuration#Writing) config which defaults to 0, so it shouldn't convert case (meaning it's case sensitive by default).

---

To clarify, you would like to merge `Java` and `java` into one? In your blog, does `Java` and `java` have different link?

**Comment by RobotWuYun** [comment]
> 如果你希望标签不区分大小写，
> 
> ```yaml
> _config.yml
> filename_case: 1
> ```
> 
> 它应该将所有标记转换为小写。

**Comment by RobotWuYun** [comment]
thinks~

**Comment by dailyrandomphoto** [comment]
I have this problem many times too.
Sometimes, I can't remember the case of each tag name used previously. Java? java? or JAVA?
I have to search the tag name to clarify. 
```sh
hexo list tag
```

If we use both `Java` and `java`, we will have problems as @RobotWuYun met. 
Since the file system can't create both /Java/ and /java/ directories, one of them will not accessible.

Exactly we want just one tag, but not both `Java` and `java`, and want to write tag name case insensitive.

To solve this problem, I wrote a plugin.
https://github.com/dailyrandomphoto/hexo-easy-tags-plugin

**Comment by dailyrandomphoto** [comment]
@RobotWuYun 
You should modify `url` in `_config.yml`.
```diff
# _config.yml

- url: http://yoursite.com
+ url: https://robotwuyun.github.io
```
<img width="806" alt="2019112801" src="https://user-images.githubusercontent.com/51783821/69809039-de3e4680-1223-11ea-928d-8032941f98ca.png">

**Comment by curbengh** [comment]
> Since the file system can't create both /Java/ and /java/ directories, one of them will not accessible.

It's possible in [case-sensitive](https://en.wikipedia.org/wiki/Case_preservation) file systems.

> To solve this problem, I wrote a plugin.
> https://github.com/dailyrandomphoto/hexo-easy-tags-plugin

Is the plugin still required if `filename_case: 1` is set?

**Comment by dailyrandomphoto** [comment]
Yes, because `filename_case: 1` can't solve this problem.

### Without this plugin
- filename_case: 0
post-a.md
```yaml
tags:
  - JAVA
```
=> tag name: JAVA, slug: /JAVA/

post-b.md
```yaml
tags:
  - java
```
=> tag name: java, slug: /java/

Only one of /JAVA/ and /java/ will be created on case-insensitive file systems. (Mac, Windows).

- filename_case: 1
post-a.md
```yaml
tags:
  - JAVA
```
=> tag name: JAVA, slug: /java/

post-b.md
```yaml
tags:
  - java
```
=> tag name: java, slug: /java/

Only one of post-a.md and post-b.md will be created under /java/, because `JAVA` and `java` are two different tags.


### With this plugin
- filename_case: 0
post-a.md
```yaml
tags:
  - JAVA
```

post-b.md
```yaml
tags:
  - java
```
=> Automaticaly corrects `java` to `JAVA`, or corrects `JAVA` to `java`
tag name: JAVA, slug: /JAVA/

- filename_case: 1
post-a.md
```yaml
tags:
  - JAVA
```

post-b.md
```yaml
tags:
  - java
```
=> Automaticaly corrects `java` to `JAVA`, or corrects `JAVA` to `java`
tag name: JAVA, slug: /java/

**Comment by RobotWuYun** [comment]
@dailyrandomphoto Thinks for your advice~

**Comment by curbengh** [comment]
@dailyrandomphoto 
To clarify, currently `filename_case:` only applies to post/page filename, but not tag/category?

Looks like tag/category doesn't pass `filename_case:` option into [`slugize()`](https://github.com/hexojs/hexo-util/#slugizestr-options). I'll have a check.

**Comment by dailyrandomphoto** [comment]
IMHO, tag name and category name should not be transformed. (#3912)
1. Users want to see the tag name and category name the same as what he wrote, just like the title. 
2. For example `C/C++` is converted to `c-c`. Of course this is not what users want.

This issue is due to the user wrote two tag names `Java` and` java` in another post. 
Therefore, the user does not get the desired result. (The reason is described above  https://github.com/hexojs/hexo/issues/3875#issuecomment-559625332)

You can try to add two posts like these:

- post1.md
```yml
title: About Java
tag:
  - Java
```

- post2.md
```yml
title: Another post about java
tag:
  - java
```

and check the `/tags/java/` URL.
You will see only one post, whatever `filename_case: 0` or `filename_case: 1`.

**Comment by curbengh** [comment]
So, https://github.com/hexojs/hexo/pull/3912 is not the correct approach.

Another approach I can think of is transform the case (if `filename_case:` is enabled) when saving to the database, while still retaining the original case. Not sure if this is possible.

**Comment by mutoo** [comment]
I came across the same issue, that I have 5 posts. 

- 4 of them are tagged with `processing`, and 
- 1 of them is tagged with `Processing`.

I have also set the `filename_case: 1`.
But the `/tags/processing` page only shows one post that is tagged with `Processing`.

The problem is gone if I change the `Processing` one to `processing`, then I have 5 posts on `/tags/processing` page.

**Comment by dailyrandomphoto** [comment]
@mutoo This plugin will help you solve this issue.
https://github.com/dailyrandomphoto/hexo-easy-tags-plugin

**Comment by mutoo** [comment]
hi @dailyrandomphoto , thanks for your solution. But I think that is not what I really want.

I prefer to keep those tags for certain terms (e.g. iOS, LaTex) to stay what they should be in the articles while being lowercased in the slug (e.g /tag/ios/, /tag/latex).

Currently, I am using a simple script to report those conflicting tags in my posts, and I'll make them consistent manually:
https://gist.github.com/mutoo/b82b3a05b5247d033e5b143bb7114763

**Comment by SukkaW** [comment]
> Since the file system can't create both /Java/ and /java/ directories, one of them will not accessible.

@dailyrandomphoto Most *unix file system are case-sensitive (APFS is case-insensitive by default, but can be enabled after a format). Even the Windows has an option to enable case-insensitive for NTFS.

Unless the hosting that serves the site are using Windows or macOS, we have no need to concern inaccessible tags.

**Comment by dailyrandomphoto** [comment]
> Most *nix file system are case-sensitive (APFS is case-insensitive by default, but can be enabled after a format). Even the Windows has an option to enable case-sensitive for NTFS.
> 
> Unless the hosting that serves the site are using Windows or macOS, we have no need to concern inaccessible tags.

Although we can enable case sensitivity on Windows and macOS, I think the case-insensitive file system is a common environment for users.

Another problem is that if the `filename_case: 1` option is set, we cannot use `Java` and `java` tags at the same time, even in a case-sensitive file system.

As the number of posts increases, it becomes difficult to remember which text case was used in previously used tag names.

This is a pain for me (and others). To solve this I wrote [this plugin](https://github.com/dailyrandomphoto/hexo-easy-tags-plugin). It corrects tag name automatically.

**Comment by dailyrandomphoto** [comment]
> I prefer to keep those tags for certain terms (e.g. iOS, LaTex) to stay what they should be in the articles while being lowercased in the slug (e.g /tag/ios/, /tag/latex).

@mutoo 
You can try this configuration.
```yaml
# _config.yml
filename_case: 1 # lowercased in the slug

easy_tags_plugin:
  enable: true
  tag_name_case: 0  # 0 no transform
```

Your script functions similarly to my plugin. One reports the conflicted tag name and the other automatically corrects the tag name.
I plan to add a new option in the next release to enable reporting conflicts instead of automatic corrections.
