### ISSUE TITLE
测试hexo4.0/next7.5出现的几个bug

### ISSUE THREAD

**Issue by ElfriedeMagdaleneHolger** [hexojs/hexo#3876]
1.我看见package里面有集成hexo-generator-archive等插件，但我按照配置设置按月归档之后不起效果，我又按照网上的教程单独安装了一遍，配置依然不起效果
2.根据a href链接会自动生成target：_blank那个问题里，我设置了external_link在站点config里，但无法正常hexo g，会报错，下载了文件包里最新的lib文件夹替换后也没有效果，所以现在我的搜索功能依然会自动打开about:blank#blocked界面
3.sidebar里面的site-state里面不是有日志，分类和标签三个总数的统计嘛，其点击去可以分别进入日志分类和标签的菜单界面，但我最近发现a href莫名变成了
`          <a href="/archives/%20%7C%7C%20archive">
           <span class="site-state-item-count">66</span>
          <span class="site-state-item-name">日志</span>`

第一行里面/archives/后面莫名多了很多%20%7C%7C%20部分导致其没法正常进入archive界面，但这个我只能在网页f12里面调试，不知道在本地文件夹里应该怎么解决？

**Comment by curbengh** [comment]
> 根据a href链接会自动生成target：_blank那个问题里
Maybe related to https://github.com/hexojs/hexo-util/issues/122, which has been fixed by https://github.com/hexojs/hexo-util/pull/130, to be released in hexo-util [1.6.0](https://github.com/hexojs/hexo-util/pull/133).

> `"/archives/%20%7C%7C%20archive"`

That's [url encoding](https://www.cnblogs.com/DaoMuRen/p/5695030.html), which is equivalent to `"/archives/ || archive"`. But the value should be `"/archives/"` though. Can you attach the sidebar config (of next theme)? @stevenjoezhang can you help?

**Comment by stevenjoezhang** [comment]
The official website of the theme NexT is a successful example: https://github.com/theme-next/theme-next.org
https://theme-next.org/
At least it seems that the master branch of theme NexT has no compatibility issues with Hexo 4.0.
NexT version 7.6.0 will be released on December 1st, which should resolve all known issues.
