### ISSUE TITLE
Introduce a bootcamp slide for hexo beginner - Discover GitHub with Hexo 

### ISSUE THREAD

**Issue by Leslie-Wong-H** [hexojs/hexo#3903]
About two monthes ago I hosted a bootcamp lecture about hexo to CS sophomore at my university. This is the slide for it. 

https://www.lesliewong.cn/github/DiscoverGitHubwithHexo.pdf

Hope this slide would be of a little help to the hexo community. 

If there are any mistake in this slide, please feel free to point out, even though some students did build up their own website after this lecture.

**Comment by SukkaW** [comment]
**page 3**

![image](https://user-images.githubusercontent.com/40715044/70692039-7d1f7400-1cf5-11ea-8f06-6f00ea02e62f.png)

Hexo doesn't require GitHub. Although Hexo could be deployed to GitHub Pages but it is not the only available options. I see no necessary introducing GitHub.

**page 5**

![image](https://user-images.githubusercontent.com/40715044/70692170-ba840180-1cf5-11ea-9a79-0ce78941372a.png)

Hexo only requires Node.js & Git, which means Hexo CAN run on any VPS.


**page 8**

![image](https://user-images.githubusercontent.com/40715044/70692327-12226d00-1cf6-11ea-8d8e-35c2ed8492f8.png)


`npm init` will execute `npm install` automatically. And the title should be `Install Hexo`.

**page 10 - 12**
 
Just I said, GitHub is not the only option available.

**page 15**

`hexo-deployer-git` requires specific configuration.

**page 17**

English should be used even inside screenshot.

**page 19**

Hexo is not designed for it. `.html` files under `source/` could be considered as posts and would be processed & rendered by Hexo. Extra configuration about `skip_render` might be needed. Since it is an advanced usage thus shouldn't be included in a slide.

**Comment by SukkaW** [comment]
IMHO, the style of the slide looks not so good. And PPT is really not suitable for making slide.

Here I provides an example: A brief on SSRF attack made by `orange.tw` team.

https://www.blackhat.com/docs/us-17/thursday/us-17-Tsai-A-New-Era-Of-SSRF-Exploiting-URL-Parser-In-Trending-Programming-Languages.pdf

**Comment by Leslie-Wong-H** [comment]
Thanks for the sincere constructive comment. Appreciate it a lot! 

As for the slide style, everyone has his own taste of art. :)
