### ISSUE TITLE
为什么我的github pages会是这样？不是yhytj.giyhub.io?

### ISSUE THREAD

**Issue by yhybulider** [hexojs/hexo#4006]
1![image](https://user-images.githubusercontent.com/48554508/71395007-0cf6e380-264f-11ea-8649-d643c796bef6.png)
repository 名字在这里
2![image](https://user-images.githubusercontent.com/48554508/71395030-2dbf3900-264f-11ea-9dea-e1501c31c0d5.png)

**Comment by dailyrandomphoto** [comment]
Because your username is `yhybulider`, not `yhytj`.

https://pages.github.com/
<img width="1030" alt="2019122401" src="https://user-images.githubusercontent.com/51783821/71399797-c6f64b80-265f-11ea-879d-6f135b6284de.png">

You can create an organization named `yhytj`, then transfer the `yhytj.github.io` repo to it.

**Comment by yhybulider** [comment]
Thanks

**Comment by yhybulider** [comment]
Thank you！！

**Comment by yhybulider** [comment]
> Because your username is yhybulider, not yhytj.
> https://pages.github.com/
> 
> You can create an organization named yhytj, then transfer the yhytj.github.io repo to it.

Thank you!!!

**Comment by dailyrandomphoto** [comment]
You're welcome.
