### ISSUE TITLE
Hexo Server does not update the content after page refresh

### ISSUE THREAD

**Issue by vitaminac** [hexojs/hexo#4571]
## Check List

Please check followings before submitting a new issue.

- [x] I have already read [Docs page](https://hexo.io/docs/) & [Troubleshooting page](https://hexo.io/docs/troubleshooting)
- [x] I have already searched existing issues and they are not help  to me
- [x] I examined error or warning messages and it's difficult to solve
- [x] Using [the latest](https://github.com/hexojs/hexo/releases) version of Hexo (run `hexo version` to check)
- [x] Node.js is higher than [minimum required version](https://hexo.io/docs/#Minimum-required-Node-js-version)

## Expected behavior

While we are running **hexo s**, each time I save blog content and refresh the blog page, content should be updated

## Actual behavior

While we are running **hexo s**, each time I save blog content and refresh the blog page, content does not update

## How to reproduce?

    hexo s --debug

generate following message

    timestamp DEBUG Processed:  _posts/blog1.md
    timestamp DEBUG Processed:  _posts/blog2.md
    timestamp DEBUG Generator: page
    timestamp DEBUG Generator: post
    timestamp DEBUG Generator: category
    timestamp DEBUG Generator: archive
    timestamp DEBUG Generator: index
    timestamp DEBUG Generator: tag
    timestamp DEBUG Generator: asset
    timestamp INFO  Hexo is running at http://localhost:4000 . Press Ctrl+C to stop.
    timestamp DEBUG Database saved

When I update any of my blogX.md it doesn't trigger any message on the console.

## Is the problem still there under "Safe mode"?

I can not test under safe mode, server plugin will be disabled under safe mode.

## Environment & Settings

node -v -> v10.21.0
npm -v -> 6.14.8

**Your site `_config.yml`** (Optional)

https://github.com/vitaminac/blog/blob/master/_config.yml

**Your theme `_config.yml`** (Optional)

https://github.com/vitaminac/blog/blob/master/themes/Anisina/_config.yml

**Hexo and Plugin version(`npm ls --depth 0`)**

    ├── hexo@5.2.0
    ├── hexo-browsersync@0.3.0
    ├── hexo-deployer-git@2.1.0
    ├── hexo-flash@1.0.0 (git+https://github.com/vitaminac/hexo-flash.git#7160ad906031eb2e127af72af9e90bf2618b2834)
    ├── hexo-generator-archive@1.0.0
    ├── hexo-generator-category@1.0.0
    ├── hexo-generator-index@2.0.0
    ├── hexo-generator-tag@1.0.0
    ├── hexo-pdf@1.1.1 (github:vitaminac/hexo-pdf#c3da6a0b0ca29833c77f7ddd14bd168d04950c72)
    ├── hexo-renderer-ejs@1.0.0
    ├── hexo-renderer-marked@3.3.0
    ├── hexo-renderer-stylus@2.0.1
    ├── hexo-server@2.0.0
    └── hexo-tag-config@1.0.0

**Your package.json `package.json`**

    {
      "name": "hexo-site",
      "version": "0.0.0",
      "private": true,
      "scripts": {
        "build": "hexo generate",
        "clean": "hexo clean",
        "deploy": "hexo deploy",
        "server": "hexo server"
      },
      "hexo": {
        "version": "5.2.0"
      },
      "dependencies": {
        "hexo": "^5.0.0",
        "hexo-deployer-git": "^2.1.0",
        "hexo-flash": "git+https://github.com/vitaminac/hexo-flash.git",
        "hexo-generator-archive": "^1.0.0",
        "hexo-generator-category": "^1.0.0",
        "hexo-generator-index": "^2.0.0",
        "hexo-generator-tag": "^1.0.0",
        "hexo-pdf": "github:vitaminac/hexo-pdf",
        "hexo-renderer-ejs": "^1.0.0",
        "hexo-renderer-marked": "^3.0.0",
        "hexo-renderer-stylus": "^2.0.0",
        "hexo-server": "^2.0.0",
        "hexo-tag-config": "^1.0.0"
      }
    }

## Others

I'm running from window WSL2, node, npm, hexo are installed inside the WSL2.

**Comment by vitaminac** [comment]
Install NodeJS in Window it solves issue, it is more likely to be WSL2 related issue, I faced the same issue with other library & app.

**Comment by Xeppetto** [comment]
First of all, I am sorry for my broken English. Anyways, I found the solution for this issue. :)

[ Result ]
I solved this issue. This issue does not happen on WSL1, but it occurs on WSL2.
So, it will be okay if you create WSL1 distro and use it.

[ Story ]
I was very busy for several months in the year 2021 and I was not able to update my hexo blog. Then I came back to my blog and suddenly the HEXO SERVER seems not updating contents automatically. I had the same issue on WSL2 and I tried to resolve this issue. After 4~5 hours I did stupid searching on stackoverflow, github and google, I found out I had to use WSL1.

These are my distro setting.

| NAME | STATE | VERSION |
| :---: |  :---: |  :---: |
| * UbuntuWSL2 | Stopped | 2 |
| Ubuntu | Running | 1 |

I made two different distros WSL1 and WSL2. Because when WSL2 distro came out for the first time, building hexo generate on local Windows file was very slow and laggy. So I use WSL2 only for docker, and I use WSL1 for JAM stacks. And this issue does not happens on the WSL1 distroy.

So, to do this, we need to search for microsoft support user manual for WSL.
1. For now, if you set up fresh WSL, it is WSL2. So, make clean install of WSL2
2. Export WSL2 image to your local PC
3. Import WSL2 image from your PC then... Set it as WSL1 distro

Here is my command.
>  (1) wsl.exe --export Ubuntu $env:USERPROFILE\UbuntuWSL2.tar
>  (2) wsl.exe --import UbuntuWSL1 $env:USERPROFILE\UbuntuWSL1 $env:USERPROFILE\UbuntuWSL2.tar --version 1
> (means) wsl.exe --import [WSL distro name] $env:USERPROFILE\[location of the folder] $env:USERPROFILE\[zip file] --version 1
