### ISSUE TITLE
Bug:marked 和 Mathjax冲突

### ISSUE THREAD

**Issue by fuzihaofzh** [hexojs/hexo#524]
你好！ 默认的markdown解析器会把公式里的一些字符转义，导致mathjax无法解析。不知道能否更换markdown解析器？

**Comment by LiamHuang0205** [comment]
给了一个利用 JS 解决问题的办法：
<http://liam0205.me/2015/09/09/fix-conflict-between-mathjax-and-markdown/>

**Comment by crackhopper** [comment]
我从别处看来的一个办法：http://kubicode.me/2016/03/16/Hexo/Fix-Hexo-Bug-In-Mathjax/

不过这个办法还是有问题，就是\begin{equation*}\end{equation*}。这两个*会被处理成<em>。

**Comment by Tveek** [comment]
可以更换**markdow解释器**，使用**pandoc**,可以几乎完美解决问题，[https://tveek.github.io/2016/08/27/octopress-hexo-learning-experience/](url)

**Comment by familyld** [comment]
这个问题是由Hexo自带的Markdown渲染引擎和MathJax冲突引起的，解决方法很简单。更换Markdown渲染引擎就可以了。详细可以查看[我的博文](http://2wildkids.com/2016/10/06/%E5%A6%82%E4%BD%95%E5%A4%84%E7%90%86Hexo%E5%92%8CMathJax%E7%9A%84%E5%85%BC%E5%AE%B9%E9%97%AE%E9%A2%98/)。

This issue is caused by the conflict of hexo-renderer-marked(Hexo's default Markdown renderer) and MathJax. To fix this issue, you can simply change your markdown renderer. See the detail in [my blog](http://2wildkids.com/2016/10/06/%E5%A6%82%E4%BD%95%E5%A4%84%E7%90%86Hexo%E5%92%8CMathJax%E7%9A%84%E5%85%BC%E5%AE%B9%E9%97%AE%E9%A2%98/).

**Comment by ShomyLiu** [comment]
比较直接的方法，就是修改Hexo的渲染机制, node_modules/marked/lib/marked.js里面的_的转义，也很简单，改两行就可以了。具体[参考](http://shomy.top/2016/10/22/hexo-markdown-mathjax/)

**Comment by liuqinh2s** [comment]
➜  blog hexo g
INFO  Start processing
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:1022:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:804:14)

**Comment by liuqinh2s** [comment]
hexo-renderer-pandoc 无法使用，pandoc 我已经安装好了

**Comment by liuqinh2s** [comment]
➜  blog pandoc --version
pandoc 2.0.2
Compiled with pandoc-types 1.17.3, texmath 0.10, skylighting 0.4.3.2
Default user data directory: /Users/liuqinh2s/.pandoc
Copyright (C) 2006-2017 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.

**Comment by ShomyLiu** [comment]
@liuqinh2s    看错误信息我也不清楚，不过可以试试先hexo clean 再hexo g. 然后就是需要先卸载原生的mark然后在用pandoc, 我按照我笔记里面的来的，http://shomy.top/2016/10/22/hexo-markdown-mathjax/

**Comment by liuqinh2s** [comment]
原生的那个 hexo-renderer-marked 我卸载了，没有用的，我用的是 mac os x 系统
