### ISSUE TITLE
Can different pages use different layouts?

### ISSUE THREAD

**Issue by linkarys** [hexojs/hexo#959]
Sorry for this stupid question, but I am new to hexo.
I'd appreciate if anyone can provide any infomation.

**Comment by jlVidal** [comment]
@nxfifteen for me it's a pretty nasty solution, the hexo should have better ways to include new pages with different layouts.

**Comment by eventhough** [comment]
@linkarys @jlVidal @nxfifteen I just tried this out with the latest hexo version and it seems to work.

First I create a new page:

```bash
$ hexo new page foobar
```

By default /foobar will use the `page` layout, but then I added `layout:` to front matter.

```yaml
---
layout: foobar
title: foobar
date: 2016-02-05 14:42:23
---
```

This loads my custom template instead of using the default `page` layout.

**Comment by me10zyl** [comment]
@eventhough how to add custom template ? layout foobar represent foobar.ejs in theme source directory?

**Comment by NoahDragon** [comment]
@me10zyl Yes, in the theme layout folder, there should have one file name match the layout. You could refer http://www.codeblocq.com/2016/03/Create-an-Hexo-Theme-Part-2-Other-Pages/ for more details.

**Comment by SourceCipher** [comment]
@eventhough yes but that means you have to add manually pages and link them all together which is really messy. Sad that Hexo is doint nothing to make easy way to create multiple _Post like pages
